# EntityCarry Plugin Configuration
# 
# How to use:
# 1. Double-sneak (sneak twice quickly) to activate carry mode
# 2. Right-click on entities to carry them
# 3. Sneak while carrying to release entities
# 4. Use /carrytoggle to allow/disallow being carried by others

# Cooldown settings (in milliseconds)
cooldown:
  # Base cooldown for carrying entities
  base: 1000
  # Extended cooldown for carrying players
  player: 3000

# How long carry mode stays active (in milliseconds)
carry-timeout: 3000

# Entities that cannot be carried
blacklist:
  - ENDER_DRAGON
  - WITHER
  - SHULKER
  - WARDEN